#!/usr/bin/python3
"""
    https://projects.raspberrypi.org/en/projects/getting-started-with-picamera
    https://www.raspberrypi.org/documentation/usage/camera/python/README.md
    http://picamera.readthedocs.io/en/release-1.13/recipes2.html
"""

from picamera.array import PiRGBArray
from picamera import PiCamera
import time
import cv2

camera = PiCamera(resolution = (640,480))
rawCapture = PiRGBArray(camera)

time.sleep(0.1)

camera.capture(rawCapture,format="bgr")
image = rawCapture.array

print("testing picamera feed into OpenCV...")

cv2.imshow("Image",image)
cv2.waitKey(0)

print("success")

