#!/bin/bash

source ./.watching

apt_installed() {
    dpkg-query -f '${Package}\n' -W | grep "^$1\$" 2>/dev/null
}

echo "Installing basic utilities"

utils="screen git vim pv"
for p in $utils
do
    if [[ $(apt_installed $p) ]]
    then
        echo "  - $p already installed"
    else
        func() {
            sudo apt install -y $p
        }
        watching func "  - $p"
    fi
done

