#!/bin/bash

source ./.watching

if [[ ! $(sudo grep "Akshi" /etc/wpa_supplicant/wpa_supplicant.conf) ]]
then
    func() {
        SSID=wifinetworkname
        WPSK=plaintextpw
        sudo sed -i "s/^country=.*\$/country=US/" /etc/wpa_supplicant/wpa_supplicant.conf
        printf '\nnetwork={\n ssid="%s"\n scan_ssid=1\n psk="%s"\n}\n' $SSID $WPSK | sudo tee -a /etc/wpa_supplicant/wpa_supplicant.conf
    }
    watching func "Adding default WIFI"
else
    echo "default WIFI already present in wpa_supplicant.conf"
fi
