#!/bin/bash

cmake -D BUILD_opencv_core=ON \
    -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D OPENCV_EXTRA_MODULES_PATH=/media/32GFLASH/opencv/opencv_contrib-3.4.3/modules \
    -D BUILD_EXAMPLES=ON \
    -D HDF5_INCLUD_DIRS=/usr/include/hdf5/serial \
    ..

